<?php
$MACW = array (
  'site' => 
  array (
    'id' => '3',
    'pass' => '',
    'token' => 'M03oLol0uOIOg0zOfouWkpzMO0O0O',
    'gzd' => '',
    'gzi' => '',
    'gzl' => '',
    'wzyd' => '',
    'wzyi' => '',
    'wzyl' => '',
    'gjcac' => '哈哈',
    'gjcad' => '2222',
    'gjcai' => '',
    'gjcal' => '',
    'gjcbc' => '',
    'gjcbd' => '',
    'gjcbi' => '',
    'gjcbl' => '',
    'gjccc' => '',
    'gjccd' => '',
    'gjcci' => '',
    'gjccl' => '',
    'gjcdc' => '',
    'gjcdd' => '',
    'gjcdi' => '',
    'gjcdl' => '',
    'dyn' => '3',
    'dyc' => '电影',
    'xsn' => '2',
    'xsc' => '小说',
    'tkn' => '',
    'tkc' => '',
    'tkca' => '',
    'udn' => '5',
    'udc' => '小说',
    'udl' => '',
    'notalk' => '',
    'gjcan' => '1',
    'gjcbn' => '',
    'gjccn' => '',
    'gjcdn' => '',
    'udcn' => '4',
  ),
);
?>